Repository InvoicePlane/InvoicePlane, pull requests merged in 2018-04, with the labels that each got.

#615 Fixes for IP-686 IP-680 and IP-687
  application/modules/invoices/views/index_recurring.php
  application/modules/layout/views/includes/head.php
  application/modules/user_clients/views/field.php
Labels: Ready to merge

#616 [IP-681] Add more schedules for recurring invoices
  application/language/english/ip_lang.php
  application/modules/invoices/models/Mdl_invoices_recurring.php
Labels: Ready to merge

#613 Updating build paths.
  assets/invoiceplane/sass/style.scss
  assets/invoiceplane_blue/sass/style.scss
Labels: Ready to merge

#611 [IP-679] - Duplicate invoice number generation
  application/modules/invoices/models/Mdl_invoices.php
  application/modules/quotes/models/Mdl_quotes.php
Labels: Ready to merge

#617 [IP-688] Make 'default_list_limit' more customizable
  application/modules/settings/views/partial_settings_general.php
Labels: Ready to merge

#550 [IP-691] Provide new log file for fail2ban
  application/modules/sessions/controllers/Sessions.php
Labels: Needs review, Work in Progress

#588 [IP-636] Add another quote state "invoiced"
  application/modules/quotes/controllers/Ajax.php
  application/modules/quotes/controllers/Quotes.php
  application/modules/quotes/models/Mdl_quotes.php
  assets/core/scss/_core.scss
  assets/invoiceplane/sass/_ip_variables.scss
  assets/invoiceplane_blue/sass/_ip_variables.scss
Labels: Needs review

#628 [IP-700] - IP doesn’t generate invoice number after download
  application/modules/invoices/controllers/Invoices.php
  application/modules/quotes/controllers/Quotes.php
Labels: Ready to merge
